### ISSUE TITLE
Rename rename()

### ISSUE THREAD

**Issue by andres5791** [dopatendo/ILSAmerge#1]
rename is a very generic name for functions and is prone to overlap with other packages (e.g., dplyr::rename). Would be cool it can be changed to a more unique name. Of course it's not a big deal since we can just use ILSAmerge::rename to call it.

**Comment by dopatendo** [comment]
thanks!, I think you are right. rename() is not yet submitted to CRAN, so I think it is feasible to change it. How do you feel about ILSArename() or do you have any other suggestion?

**Comment by andres5791** [comment]
That would make sense and be consistent with the other functions of the package

**Comment by dopatendo** [comment]
function is now called ILSArename() for >=v1.0.5
